scaffold/blog/urls.py
from django.urls import path
from . import views
from .views import AllSaveView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SaveView,\
    UserPostListView, LikeView,LikeCommentView, posts_of_following_profiles,  AllLikeView, privacypolicy, support, terms

urlpatterns = [
    path('', views.first, name='firsthome'),
    path('support/', views.support, name='support'),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('privacypolicy/', privacypolicy, name='privacy-policy'),
    path('terms/', privacypolicy, name='terms'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('blog/new/', PostCreateView.as_view(), name='post-create'),
    path('post/like/', LikeView, name='post-like'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('post/save/', SaveView, name='post-save'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.search, name='search'),
]

scaffold/notification/urls.py
from django.urls import path
from notification.views import ShowNotifications

urlpatterns = [
    path('', ShowNotifications, name='show-notifications'),
]

scaffold/scaffold/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from blog.views import search


urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
    path('user/', include('users.urls')),
    path('notifications/', include('notification.urls')),
    path('chats/', include('chat.urls')),
    path('vc/', include('videocall.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('metaversemusic/', include('metaversemusic.urls')),
    path('search/', search, name='search'),
    path("__reload__/", include("django_browser_reload.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scaffold/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import os


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    vibe = models.FileField(upload_to='vibes/', blank=True, null=True)
    caption = models.TextField(max_length=500, blank=True, null=True)
    link = models.URLField(default='https://www.vibstream.com')
    tags = models.ManyToManyField(Tag, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="blogpost", blank=True)
    saves = models.ManyToManyField(User, related_name="blogsave", blank=True)

    def get_media_type(self):
        if self.vibe:
            _, ext = os.path.splitext(self.vibe.name)
            if ext.lower() in ['.mp3', '.wav', '.ogg']:
                return 'song'
            elif ext.lower() in ['.jpg', '.jpeg', '.png', '.gif']:
                return 'picture'
            elif ext.lower() in ['.mp4', '.avi', '.mov']:
                return 'video'
        return ''

    def total_likes(self):
        return self.likes.count()

    def total_saves(self):
        return self.saves.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk": self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="blogcomment", blank=True)
    reply = models.ForeignKey('self', null=True, related_name="replies", on_delete=models.CASCADE)

    def total_clikes(self):
        return self.likes.count()

    def __str__(self):
        return '%s - %s - %s' % (self.post.title, self.name, self.id)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk": self.pk})


class SupportMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    responded = models.BooleanField(default=False)
    admin_response = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username} - {self.timestamp}"

scaffold/notification/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

""" Notification model """
class Notification(models.Model):
    NOTIFICATION_TYPES = ((1,'Like'),(2,'Follow'),(3,'Comment'),(4,'Reply'),(5,'Like-Comment'),(6,'Like-Reply'))

    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='notify_post', blank=True, null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_from_user')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notify_to_user')
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=120, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s - %s - %s - %s' %(self.id, self.post, self.sender, self.user, self.notification_type)

scaffold/blog/forms.py
from django import forms
from .models import Comment, Post, SupportMessage


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control custom-txt', 'cols': '40', 'rows': '3'}),
                           label='')

    class Meta:
        model = Comment
        fields = ['body']


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}), label='')
    caption = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Caption'}), label='')
    link = forms.FileField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter song URL'}))
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}), label='Image')                              
    vibe = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
                                 label='Video')

    class Meta:
        model = Post
        fields = ['title', 'link', 'vibe', 'caption']



class SupportMessageForm(forms.ModelForm):
    class Meta:
        model = SupportMessage
        fields = ['message']

scaffold/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from PIL import Image
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField



class UserRegisterForm(UserCreationForm):
    USER_TYPE_CHOICES = (
        ('artist', 'Artist'),
        ('fan', 'Fan'),
    )

    email = forms.EmailField()
    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, initial='fan', widget=forms.RadioSelect)
    country = CountryField()

    class Meta:
        model = User
        widgets = {"country": CountrySelectWidget()}
        date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), required=False)
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']



    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        user_profile = Profile.objects.create(user=user, country=self.cleaned_data['country'], user_type=self.cleaned_data['user_type'], date_of_birth=self.cleaned_data['date_of_birth'])
        return user, user_profile



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']


class ProfileUpdateForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    image = forms.ImageField(label=('Image'), error_messages = {'invalid':("Image files only")}, widget=forms.FileInput, required=False)
    class Meta:
        model = Profile
        fields = ['bio','date_of_birth','image',]


    """Saving Cropped Image"""
    def save(self,*args,**kwargs):
        img = super(ProfileUpdateForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x and y and w and h:
            image = Image.open(img.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
            resized_image.save(img.image.path)

        return img

scaffold/notification/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from notification.models import Notification

# Create your views here.

""" All notifications """
@login_required
def ShowNotifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    context = {
        'notifications':notifications,
    }
    return render(request, 'blog/notifications.html', context)

scaffold/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
  <div class="bg-white shadow-md rounded-lg overflow-hidden">
    <div class="p-6 sm:p-8">
      <h1 class="text-3xl font-bold text-gray-900 mb-6">About page</h1>
      
      <p class="text-gray-700 mb-4">
        The idea is to create a next generation outlet for independent artists. Our platform will allow users to create
        NFT's from music, videos, and digital art, we will make it easy for fans and artists to interact using the blockchain,
        fans can purchase musical nfts and resell while creators gain royalties from each resell.
      </p>

      <p class="text-gray-700 mb-8">
        We Will be a major distributor of music NFT's and expand this new horizon for artists and fans.
      </p>

      <div class="text-center text-gray-600">
        <p>Made with <span class="text-red-500">&#128150;</span> by Kemar Henry <span class="text-yellow-500">&#9996;</span></p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

scaffold/blog/templates/blog/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" />
    
    <link rel="stylesheet" href="{% static 'blog/newstyles.css' %}">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <title>Vibstream | {% block title %}{% endblock %}</title>
    <script src="https://cdn-tailwindcss.vercel.app/"></script>

    {% tailwind_css %}
<style>
    #waveform {
      cursor: pointer;
      position: relative;
    }
    #hover {
      position: absolute;
      left: 0;
      top: 0;
      z-index: 10;
      pointer-events: none;
      height: 100%;
      width: 0;
      mix-blend-mode: overlay;
      background: rgba(255, 255, 255, 0.5);
      opacity: 0;
      transition: opacity 0.2s ease;
    }
    #waveform:hover #hover {
      opacity: 1;
    }
    #time,
    #duration {
      position: absolute;
      z-index: 11;
      top: 50%;
      margin-top: -1px;
      transform: translateY(-50%);
      font-size: 11px;
      background: rgba(0, 0, 0, 0.75);
      padding: 2px;
      color: #ddd;
    }
    #time {
      left: 0;
    }
    #duration {
      right: 0;
    }
    </style>
</head>
<body class="bg-gray-900 text-gray-100">
  <div id="layout" class="flex flex-col md:flex-row w-full">
    <div class="md:block">
      <!-- Sidebar -->
      <div id="default-sidebar" class="fixed inset-y-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full md:translate-x-0">
        {%include 'blog/partials/sidebar.html'%}
      </div>
    </div>
    <!-- Main Content -->
    <div id="main-content" role="main" class="flex-1 md:ml-64 p-4">
      <!-- Mobile Sidebar Toggle -->
      <button data-drawer-toggle class="md:hidden p-2 mb-4 text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
        <span class="sr-only">Open sidebar</span>
        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
        </svg>
      </button>

      <!-- Main Section -->
      <div class="main-content block">
        <!-- Messages -->
        <div class="main-section flex-row">
          {% if messages %}
            {% for message in messages %}
              <div class="alert {{ message.tags }} bg-orange-500 text-gray-900 p-4 mb-4 rounded">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <!-- Content -->
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      const drawerToggle = document.querySelector('[data-drawer-toggle]');
      const sidebar = document.getElementById('default-sidebar');
      drawerToggle.addEventListener('click', () => {
        sidebar.classList.toggle('-translate-x-full');
      });
    });
  </script>
</body>



    <!-- SCRIPTS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/2.0.6/wavesurfer.min.js"></script>

      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous"></script>
      
      <script>
        $(function () {
    
          /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
          $("#id_image").change(function () {
            if (this.files && this.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $("#image").attr("src", e.target.result);
                $("#modalCrop").modal('show');
              }
              reader.readAsDataURL(this.files[0]);
            }
          });
    
          /* SCRIPTS TO HANDLE THE CROPPER BOX */
          var $image = $("#image");
          var cropBoxData;
          var canvasData;
          $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
              viewMode: 1,
              aspectRatio: 1/1,
              minCropBoxWidth: 200,
              minCropBoxHeight: 200,
              ready: function () {
                $image.cropper("setCanvasData", canvasData);
                $image.cropper("setCropBoxData", cropBoxData);
              }
            });
          }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
            location.reload();
          });
    
          $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
          });
    
          $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
          });
    
          /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
          $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            // console.log(cropData);
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
          });
    
        });
      </script>

      <script type="text/javascript">

        $(document).ready(function(event){
          
          // $("#chat-box").scrollTop($("#chat-box")[0].scrollHeight);

          // LIKE POSTS

          $(document).on('click','#like',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-like" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#like-section').html(response['form']);
                  console.log($('#like-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT LIKE

          $(document).on('click','.clike',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: "{% url 'comment-like' %}",
              data: {'id':pk, 'pid':'{{post.pk}}', 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('.main-comment-section').html(response['form']);
                  console.log($('.main-comment-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // SAVE POSTS

          $(document).on('click','#save',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-save" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#save-section').html(response['form']);
                  console.log($('#save-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT FORM

          $(document).on('submit','.comment-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

          // REPLY FORM

          $(document).on('submit','.reply-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

        });






      </script>

  <!--  <script type="module">
     // WAVESURFER
import WaveSurfer from 'https://unpkg.com/wavesurfer.js@7/dist/wavesurfer.esm.js'

const canvas = document.createElement('canvas')
const ctx = canvas.getContext('2d')

// Define the waveform gradient
const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height * 1.35)
gradient.addColorStop(0, '#656666') // Top color
gradient.addColorStop((canvas.height * 0.7) / canvas.height, '#e6b812') // Top color
gradient.addColorStop((canvas.height * 0.7 + 1) / canvas.height, '#ffffff') // White line
gradient.addColorStop((canvas.height * 0.7 + 2) / canvas.height, '#ffffff') // White line
gradient.addColorStop((canvas.height * 0.7 + 3) / canvas.height, '#B1B1B1') // Bottom color
gradient.addColorStop(1, '#B1B1B1') // Bottom color

// Define the progress gradient
const progressGradient = ctx.createLinearGradient(0, 0, 0, canvas.height * 1.35)
progressGradient.addColorStop(0, '#EE772F') // Top color
progressGradient.addColorStop((canvas.height * 0.7) / canvas.height, '#EB4926') // Top color
progressGradient.addColorStop((canvas.height * 0.7 + 1) / canvas.height, '#ffffff') // White line
progressGradient.addColorStop((canvas.height * 0.7 + 2) / canvas.height, '#ffffff') // White line
progressGradient.addColorStop((canvas.height * 0.7 + 3) / canvas.height, '#F6B094') // Bottom color
progressGradient.addColorStop(1, '#F6B094') // Bottom color

// Create the waveform
const wavesurfer = WaveSurfer.create({
  container: '#waveform',
  waveColor: gradient,
  progressColor: progressGradient,
  barWidth: 2,
  url: '{{post.vibe.url}}',
})

// Play/pause on click
wavesurfer.on('interaction', () => {
  wavesurfer.playPause()
})

// Hover effect
{
  const hover = document.querySelector('#hover')
  const waveform = document.querySelector('#waveform')
  waveform.addEventListener('pointermove', (e) => (hover.style.width = `${e.offsetX}px`))
}

// Current time & duration
{
  const formatTime = (seconds) => {
    const minutes = Math.floor(seconds / 60)
    const secondsRemainder = Math.round(seconds) % 60
    const paddedSeconds = `0${secondsRemainder}`.slice(-2)
    return `${minutes}:${paddedSeconds}`
  }

  const timeEl = document.querySelector('#time')
  const durationEl = document.querySelector('#duration')
  wavesurfer.on('decode', (duration) => (durationEl.textContent = formatTime(duration)))
  wavesurfer.on('timeupdate', (currentTime) => (timeEl.textContent = formatTime(currentTime)))
}
</script>



      {% block script %}{% endblock %}

</body>
</html> -->

scaffold/blog/templates/blog/like_section.html
<form action="{% url 'post-like' %}" method="POST" class="flex items-center">
    {% csrf_token %}

    {% if user.is_authenticated %}
        {% if liked %}
            <button id="like" type="submit" name="post_id" value="{{post.id}}" class="p-2 text-red-500 hover:text-red-600 focus:outline-none">
                <i class="fas fa-heart"></i>
            </button>
        {% else %}
            <button id="like" type="submit" name="post_id" value="{{post.id}}" class="p-2 text-gray-500 hover:text-red-500 focus:outline-none">
                <i class="far fa-heart"></i>
            </button>
        {% endif %}
    {% else %}
        <small class="text-sm text-gray-500">Login to like</small>
    {% endif %}
    <span class="ml-2 text-sm text-gray-600">
        {{total_likes}} Like{{ total_likes|pluralize }}
    </span>
</form>

scaffold/blog/templates/blog/liked_posts.html
<form action="{% url 'post-like' %}" method="POST" class="flex items-center space-x-2">
  {% csrf_token %}

  {% if user.is_authenticated %}
      {% if liked %}
          <button id="like" type="submit" name="post_id" value="{{post.id}}" class="p-2 text-red-500 hover:text-red-600 focus:outline-none transition duration-300">
              <i class="fas fa-heart"></i>
          </button>
      {% else %}
          <button id="like" type="submit" name="post_id" value="{{post.id}}" class="p-2 text-gray-400 hover:text-red-500 focus:outline-none transition duration-300">
              <i class="far fa-heart"></i>
          </button>
      {% endif %}
  {% else %}
      <span class="text-sm text-gray-500">Login to like</span>
  {% endif %}
  <span class="text-sm text-gray-600">
      {{total_likes}} Like{{ total_likes|pluralize }}
  </span>
</form>

scaffold/blog/templates/blog/save_section.html
<form class="d-inline float-right" action="{% url 'post-save' %}" method="POST">
    {% csrf_token %}

    {% if user.is_authenticated %}
        {% if saved %}
            <button id="save" type="submit" name="post_sid" value="{{post.id}}" class="btn btnsave"><i class="fas fa-bookmark"></i></button>
        {% else %}
            <button id="save" type="submit" name="post_sid" value="{{post.id}}" class="btn btnsave"><i class="far fa-bookmark"></i></button>
        {% endif %}
    {% endif %}
</form>