scaffold/blog/urls.py
from django.urls import path
from . import views
from .views import AllSaveView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SaveView,\
    UserPostListView, LikeView,LikeCommentView, posts_of_following_profiles,  AllLikeView, privacypolicy, support, terms

urlpatterns = [
    path('', views.first, name='firsthome'),
    path('support/', views.support, name='support'),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('privacypolicy/', privacypolicy, name='privacy-policy'),
    path('terms/', privacypolicy, name='terms'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('blog/new/', PostCreateView.as_view(), name='post-create'),
    path('post/like/', LikeView, name='post-like'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('post/save/', SaveView, name='post-save'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.search, name='search'),
]

scaffold/metaversemusic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *


app_name = "metaversemusic"

urlpatterns = [
    path('createnft/', CreateNFTView.as_view(), name='createnft'),
    path('nftsmarket/', nftsmarket, name='nftsmarket'),
    path('nft/<int:nft_id>/', MintingDetailsView.as_view(), name='minting-detail'),
    path('playlists/', PlaylistListView.as_view(), name='playlist-list'),
    path('playlists/<int:pk>/', PlaylistDetailView.as_view(), name='playlist-detail'),
    path('playlists/create/', PlaylistCreateView.as_view(), name='playlist-create'),
    path('charts/', ChartsListView.as_view(), name='charts-list'),
    path('charts/<int:pk>/', ChartsDetailView.as_view(), name='charts-detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scaffold/scaffold/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from blog.views import search


urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('accounts/', include('allauth.urls')),
    path('', include('blog.urls')),
    path('user/', include('users.urls')),
    path('notifications/', include('notification.urls')),
    path('chats/', include('chat.urls')),
    path('vc/', include('videocall.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('metaversemusic/', include('metaversemusic.urls')),
    path('search/', search, name='search'),
    path("__reload__/", include("django_browser_reload.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scaffold/blog/forms.py
from django import forms
from .models import Comment, Post, SupportMessage


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control custom-txt', 'cols': '40', 'rows': '3'}),
                           label='')

    class Meta:
        model = Comment
        fields = ['body']


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}), label='')
    caption = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Caption'}), label='')
    link = forms.FileField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter song URL'}))
    image = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}), label='Image')                              
    vibe = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
                                 label='Video')

    class Meta:
        model = Post
        fields = ['title', 'link', 'vibe', 'caption']



class SupportMessageForm(forms.ModelForm):
    class Meta:
        model = SupportMessage
        fields = ['message']

scaffold/blog/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Comment, Post
from .forms import CommentForm
from django.http import HttpResponseRedirect, JsonResponse
from users.models import Profile
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
import random
from blog.utils import is_ajax
from django.core.files.storage import FileSystemStorage
from notification.models import Notification
import re
from .forms import SupportMessageForm
from .models import SupportMessage
from django.contrib import messages

def terms(request):
    return render(request, 'blog/terms.html')


@login_required
def support(request):
    if request.method == 'POST':
        form = SupportMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.user = request.user
            message.save()
            return redirect('support')

        admin_response = request.POST.get('admin_response')
        if admin_response and request.user.is_staff:
            message_id = request.POST.get('message_id')
            try:
                message = SupportMessage.objects.get(id=message_id)
                message.admin_response = admin_response
                message.responded = True
                message.save()
                message.success(request, 'Admin response sent successfully.')
            except SupportMessage.DoesNotExist:
                pass

            return redirect('support')
    else:
        form = SupportMessageForm()

    messages = SupportMessage.objects.filter(user=request.user).order_by('-timestamp')

    context = {
        'form': form,
        'messages': messages,
    }
    return render(request, 'blog/support.html', context)


def privacypolicy(request):
    return render(request, 'blog/privacypolicy.html')


def first(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/first.html', context)


""" Posts of following user profiles """


@login_required
def posts_of_following_profiles(request):
    profile = Profile.objects.get(user=request.user)
    users = [user for user in profile.following.all()]
    posts = []
    qs = None
    for u in users:
        p = Profile.objects.get(user=u)
        p_posts = p.user.post_set.all()
        posts.append(p_posts)
    my_posts = profile.profile_posts()
    posts.append(my_posts)
    if len(posts) > 0:
        qs = sorted(chain(*posts), reverse=True, key=lambda obj: obj.date_posted)

    paginator = Paginator(qs, 5)
    page = request.GET.get('page')
    try:
        posts_list = paginator.page(page)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)

    return render(request, 'blog/feeds.html', {'profile': profile, 'posts': posts_list})


""" Post Like """


@login_required
def LikeView(request):
    post = get_object_or_404(Post, id=request.POST.get('id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
        notify = Notification.objects.filter(post=post, sender=request.user, notification_type=1)
        notify.delete()
    else:
        post.likes.add(request.user)
        liked = True
        notify = Notification(post=post, sender=request.user, user=post.author, notification_type=1)
        notify.save()

    context = {
        'post': post,
        'total_likes': post.total_likes(),
        'liked': liked,
    }

    if is_ajax(request=request):
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})


""" Post save """


@login_required
def SaveView(request):
    post = get_object_or_404(Post, id=request.POST.get('id'))
    saved = False
    if post.saves.filter(id=request.user.id).exists():
        post.saves.remove(request.user)
        saved = False
    else:
        post.saves.add(request.user)
        saved = True

    context = {
        'post': post,
        'total_saves': post.total_saves(),
        'saved': saved,
    }

    if is_ajax(request=request):
        html = render_to_string('blog/save_section.html', context, request=request)
        return JsonResponse({'form': html})


""" Like post comments """


@login_required
def LikeCommentView(request):  # , id1, id2              id1=post.pk id2=reply.pk
    post = get_object_or_404(Comment, id=request.POST.get('id'))
    cliked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        cliked = False
    else:
        post.likes.add(request.user)
        cliked = True

    cpost = get_object_or_404(Post, id=request.POST.get('pid'))
    total_comments2 = cpost.comments.all().order_by('-id')
    total_comments = cpost.comments.all().filter(reply=None).order_by('-id')
    tcl = {}
    for cmt in total_comments2:
        total_clikes = cmt.total_clikes()
        cliked = False
        if cmt.likes.filter(id=request.user.id).exists():
            cliked = True

        tcl[cmt.id] = cliked

    context = {
        'comment_form': CommentForm(),
        'post': cpost,
        'comments': total_comments,
        'total_clikes': post.total_clikes(),
        'clikes': tcl
    }

    if is_ajax(request=request):
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})


""" Home page with all posts """

from sorl.thumbnail import get_thumbnail

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        from django.core.files.storage import default_storage
        context = super(PostListView, self).get_context_data(**kwargs)
        users = list(User.objects.exclude(pk=self.request.user.pk))
        cnt = min(3, len(users))  # Ensures cnt is not greater than the number of users
        random_users = random.sample(users, cnt)
        context['random_users'] = random_users
        
        # Add thumbnails for each post
        for post in context['posts']:
            if post.image and default_storage.exists(post.image.name):
                post.thumbnail = get_thumbnail(post.image, '100x100', crop='center', quality=99)
            else:
                post.thumbnail = None

        
        return context


""" All the posts of the user """


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


""" Post detail view 


def PostDetailView(request, pk):
    stuff = get_object_or_404(Post, id=pk)
    total_likes = stuff.total_likes()
    total_saves = stuff.total_saves()
    total_comments = stuff.comments.all().filter(reply=None).order_by('-id')
    total_comments2 = stuff.comments.all().order_by('-id')
    post = Post.objects.get(pk=pk)
    media_type = post.get_media_type()

    context = {
        'post': post,
        'media_type': media_type,
    }

    if request.method == "POST":
        comment_qs = None
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            form = request.POST.get('body')
            reply_id = request.POST.get('comment_id')
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)

            comment = Comment.objects.create(name=request.user, post=stuff, body=form, reply=comment_qs)
            comment.save()
            if reply_id:
                notify = Notification(post=stuff, sender=request.user, user=stuff.author, text_preview=form,
                                      notification_type=4)
                notify.save()
            else:
                notify = Notification(post=stuff, sender=request.user, user=stuff.author, text_preview=form,
                                      notification_type=3)
                notify.save()
            total_comments = stuff.comments.all().filter(reply=None).order_by('-id')
            total_comments2 = stuff.comments.all().order_by('-id')
    else:
        comment_form = CommentForm()

    tcl = {}
    for cmt in total_comments2:
        total_clikes = cmt.total_clikes()
        cliked = False
        if cmt.likes.filter(id=request.user.id).exists():
            cliked = True

        tcl[cmt.id] = cliked
    context["clikes"] = tcl

    liked = False
    if stuff.likes.filter(id=request.user.id).exists():
        liked = True
    context["total_likes"] = total_likes
    context["liked"] = liked

    saved = False
    if stuff.saves.filter(id=request.user.id).exists():
        saved = True
    context["total_saves"] = total_saves
    context["saved"] = saved

    context['comment_form'] = comment_form

    context['post'] = stuff
    context['comments'] = total_comments

    if is_ajax(request=request):
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', context)
    
    """

def PostDetailView(request, pk):
    model= Post
    stuff = get_object_or_404(Post, id=pk)
    total_likes = stuff.total_likes()

scaffold/blog/templates/blog/partials/navbar.html
<nav class="mt-4 px-3">
  <a class="text-xl font-bold text-gray-100 block mb-6" href="/">Vibstream</a>
  <div class="mt-8 space-y-4">
      <form method="GET" action="/search" class="relative">
          <input required name="query" id="search" type="text" placeholder="Search" class="w-full px-4 py-2 text-gray-700 bg-gray-800 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600">
          <button type="submit" class="absolute right-0 top-0 mt-2 mr-4">
              <svg class="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
          </button>
      </form>

  <ul class="space-y-2">

      <li><a href="{% url 'blog-home' %}" class="flex py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700">Home</a></li>
      <li>
          <button class="flex items-center justify-between w-full py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700" onclick="toggleDropdown('metaVerseMusic')">
              <span>MetaVerseMusic</span>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
          </button>
          <ul id="metaVerseMusic" class="hidden pl-4 mt-2 space-y-2">
              <li><a href="{% url 'metaversemusic:nftsmarket' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">NFT Marketplace</a></li>
              <li><a href="{% url 'metaversemusic:createnft' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Mint NFT</a></li>
              <li><a href="{% url 'metaversemusic:charts-list' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Charts</a></li>
              <li><a href="{% url 'metaversemusic:playlist-list' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Playlists</a></li>
              <li><a href="{% url 'metaversemusic:playlist-create' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Create Playlist</a></li>
          </ul>
      </li>
      <li>
          <button class="flex items-center justify-between w-full py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700" onclick="toggleDropdown('newPostTitles')">
              <span>New Post Titles</span>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
          </button>
          <ul id="newPostTitles" class="hidden pl-4 mt-2 space-y-2">
              {% for post in posts|slice:":5" %}
                  <li><a href="{% url 'post-detail' post.pk %}" class="block py-2 px-4 text-sm hover:bg-gray-700">{{ post.title }}</a></li>
              {% endfor %}
          </ul>
      </li>
      
      <li>
          <button class="flex items-center justify-between w-full py-2.5 px-4 rounded transition duration-200 hover:bg-gray-700" onclick="toggleDropdown('whoToFollow')">
              <span>Who to Follow</span>
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
          </button>
          <ul id="whoToFollow" class="hidden pl-4 mt-2 space-y-2">
              {% for user in random_users %}
                  <li><a href="{% url 'profile-detail-view' user.pk %}" class="block py-2 px-4 text-sm hover:bg-gray-700">{{ user.username }}</a></li>
              {% endfor %}
          </ul>
      </li>
  </ul>

 

      {% if user.is_authenticated %}
          <a href="{% url 'show-notifications' %}" class="block py-2 px-4 hover:bg-gray-700">Notifications</a>
          <a href="{% url 'room-enroll' %}" class="block py-2 px-4 hover:bg-gray-700">Chats</a>

          <div class="relative group">
              <button class="flex items-center justify-between w-full py-2 px-4 hover:bg-gray-700" onclick="toggleDropdown('vibes')">
                  <span>Vibes</span>
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
              </button>
              <ul id="vibes" class="hidden pl-4 mt-2 space-y-2">
                  <li><a href="{% url 'post-create' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Add Vibe</a></li>
                  <li><a href="{% url 'posts-follow-view' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Feeds</a></li>
                  <li><a href="{% url 'all-like' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Likes</a></li>
                  <li><a href="{% url 'all-save' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Saves</a></li>
                  <li><a href="{% url 'blog-home' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">All Vibes</a></li>
                  <li><a href="{% url 'user-posts' user %}" class="block py-2 px-4 text-sm hover:bg-gray-700">My Vibes</a></li>
              </ul>
          </div>

          <div class="relative group">
              <button class="flex items-center justify-between w-full py-2 px-4 hover:bg-gray-700" onclick="toggleDropdown('userMenu')">
                  <span>{{user|truncatechars:"10"}}</span>
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg>
              </button>
              <ul id="userMenu" class="hidden pl-4 mt-2 space-y-2">
                  <li><a href="{% url 'profile' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Profile</a></li>
                 <i class="fas fa-settings mr-2"><a href="{% url 'profile' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Settings</a> <li></li>
                  <li><a href="{% url 'password_reset' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Change Password</a></li>
                  <li><a href="{% url 'logout' %}" class="block py-2 px-4 text-sm hover:bg-gray-700">Logout</a></li>
              </ul>
          </div>
      {% else %}
          <a href="{% url 'login' %}" class="block py-2 px-4 hover:bg-gray-700">Login</a>
          <a href="{% url 'register' %}" class="block py-2 px-4 hover:bg-gray-700">Sign Up</a>
      {% endif %}
  </div>
</nav>

scaffold/blog/templates/blog/partials/post.html
{% load static %}
{% load thumbnail %}
<div id="newPost" class="w-full">
    {% for post in posts %}
    <div class="flex flex-col bg-gray-800 rounded-lg shadow-md p-4 mb-4">
        <div class="flex items-center justify-between mb-2">
            <small class="text-gray-600">{{ post.author }}</small>
            <a href="{% url 'post-detail' post.id %}" class="text-blue-500 hover:text-blue-700">
                <h2 class="font-bold">{{ post.title }}</h2>
            </a>
        </div>

        <div class="flex items-center space-x-4">
            {% thumbnail item.image "100x100" crop="center" as im %}
    <img src="{static 'img/default.png'}" alt="Cover Art" class="w-16 h-16 object-cover rounded" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}
            <img src="{{post.cover_art.url }}" alt="Cover Art" class="w-16 h-16 object-cover rounded">
            <div id="waveform-{{ post.id }}" class="flex-grow w-96"></div>
            <button id="playBtn-{{ post.id }}" class="bg-gray-500 text-white rounded-full p-2">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path>
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                </svg>
            </button>
        </div>

        <div class="flex items-center space-x-4 mt-2">
            <small class="flex items-center">
                <button class="text-red-500 mr-1">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
                    </svg>
                </button>
                <span>{{ post.likes_count }}</span>
            </small>
            <small class="flex items-center">
                <button class="text-blue-500 mr-1">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path>
                    </svg>
                </button>
                <span>{{ post.comments_count }}</span>
            </small>
            <small class="flex items-center">
                <svg class="w-5 h-5 text-gray-500 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
                </svg>
                <span>{{ post.play_count }}</span>
            </small>
        </div>
    </div>

  <script>
    document.addEventListener('DOMContentLoaded', async function() {
    const postId = '{{ post.id }}';
    const waveformContainer = document.getElementById(`waveform-${postId}`);
    const playBtn = document.getElementById(`playBtn-${postId}`);

    playBtn.disabled = true;

    const wavesurfer = WaveSurfer.create({
        container: waveformContainer,
        waveColor: 'violet',
        progressColor: 'purple',
        cursorColor: 'navy',
        barWidth: 2,
        barRadius: 3,
        cursorWidth: 1,
        height: 50,
        barGap: 3,
        backend: 'WebAudio',
        responsive: true,
        partialRender: true
    });

    try {
        // First, load a small portion of the audio to generate the waveform
        const response = await fetch('{{ post.vibe.url }}', { headers: { 'Range': 'bytes=0-100000' } });
        const arrayBuffer = await response.arrayBuffer();
        const audioContext = new (window.AudioContext || window.webkitAudioContext)();
        const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);

        // Load the partial buffer to display the waveform
        wavesurfer.loadDecodedBuffer(audioBuffer);

        // Now, load the full audio in the background
        const fullResponse = await fetch('{{ post.vibe.url }}');
        const fullArrayBuffer = await fullResponse.arrayBuffer();
        const fullAudioBuffer = await audioContext.decodeAudioData(fullArrayBuffer);

        // Replace the partial buffer with the full one
        wavesurfer.loadDecodedBuffer(fullAudioBuffer);

        playBtn.disabled = false;
    } catch (error) {
        console.error('Error loading audio:', error);
        waveformContainer.innerHTML = 'Audio preview unavailable';
        return;
    }

    playBtn.addEventListener('click', function() {
        wavesurfer.playPause();
        this.innerHTML = wavesurfer.isPlaying() ? 
            '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 9v6m4-6v6m7-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>' : 
            '<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>';
    });
});

  </script>

    {% endfor %}
</div>